//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atomex.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("atomex.Resources.AppResources.ru", typeof(AppResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        internal static string UnderstandButton {
            get {
                return ResourceManager.GetString("UnderstandButton", resourceCulture);
            }
        }
        
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        internal static string MainNetButton {
            get {
                return ResourceManager.GetString("MainNetButton", resourceCulture);
            }
        }
        
        internal static string TestNetButton {
            get {
                return ResourceManager.GetString("TestNetButton", resourceCulture);
            }
        }
        
        internal static string PasswordEntryPlaceholder {
            get {
                return ResourceManager.GetString("PasswordEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string PasswordConfirmationEntryPlaceholder {
            get {
                return ResourceManager.GetString("PasswordConfirmationEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string AddressEntryPlaceholder {
            get {
                return ResourceManager.GetString("AddressEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string AmountEntryPlaceholder {
            get {
                return ResourceManager.GetString("AmountEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string UseDefaultFeeLabel {
            get {
                return ResourceManager.GetString("UseDefaultFeeLabel", resourceCulture);
            }
        }
        
        internal static string FeeLabel {
            get {
                return ResourceManager.GetString("FeeLabel", resourceCulture);
            }
        }
        
        internal static string FeeRateLabel {
            get {
                return ResourceManager.GetString("FeeRateLabel", resourceCulture);
            }
        }
        
        internal static string ConfirmationLabel {
            get {
                return ResourceManager.GetString("ConfirmationLabel", resourceCulture);
            }
        }
        
        internal static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        internal static string MinimumAmountLabel {
            get {
                return ResourceManager.GetString("MinimumAmountLabel", resourceCulture);
            }
        }
        
        internal static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        internal static string TransactionTime {
            get {
                return ResourceManager.GetString("TransactionTime", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string MinLabel {
            get {
                return ResourceManager.GetString("MinLabel", resourceCulture);
            }
        }
        
        internal static string MaxButton {
            get {
                return ResourceManager.GetString("MaxButton", resourceCulture);
            }
        }
        
        internal static string IdLabel {
            get {
                return ResourceManager.GetString("IdLabel", resourceCulture);
            }
        }
        
        internal static string MyWalletsButton {
            get {
                return ResourceManager.GetString("MyWalletsButton", resourceCulture);
            }
        }
        
        internal static string CreateNewWalletButton {
            get {
                return ResourceManager.GetString("CreateNewWalletButton", resourceCulture);
            }
        }
        
        internal static string RestoreWalletButton {
            get {
                return ResourceManager.GetString("RestoreWalletButton", resourceCulture);
            }
        }
        
        internal static string SelectWalletLabel {
            get {
                return ResourceManager.GetString("SelectWalletLabel", resourceCulture);
            }
        }
        
        internal static string MyWalletsTitle {
            get {
                return ResourceManager.GetString("MyWalletsTitle", resourceCulture);
            }
        }
        
        internal static string UnlockTitle {
            get {
                return ResourceManager.GetString("UnlockTitle", resourceCulture);
            }
        }
        
        internal static string UnlockLabel {
            get {
                return ResourceManager.GetString("UnlockLabel", resourceCulture);
            }
        }
        
        internal static string UnlockButton {
            get {
                return ResourceManager.GetString("UnlockButton", resourceCulture);
            }
        }
        
        internal static string UseBiometric {
            get {
                return ResourceManager.GetString("UseBiometric", resourceCulture);
            }
        }
        
        internal static string CreateNewWalletPageTitle {
            get {
                return ResourceManager.GetString("CreateNewWalletPageTitle", resourceCulture);
            }
        }
        
        internal static string RestoreWalletPageTitle {
            get {
                return ResourceManager.GetString("RestoreWalletPageTitle", resourceCulture);
            }
        }
        
        internal static string WalletTypeStepLabel {
            get {
                return ResourceManager.GetString("WalletTypeStepLabel", resourceCulture);
            }
        }
        
        internal static string SelectTypeLabel {
            get {
                return ResourceManager.GetString("SelectTypeLabel", resourceCulture);
            }
        }
        
        internal static string WalletNameStepLabel {
            get {
                return ResourceManager.GetString("WalletNameStepLabel", resourceCulture);
            }
        }
        
        internal static string EnterNameLabel {
            get {
                return ResourceManager.GetString("EnterNameLabel", resourceCulture);
            }
        }
        
        internal static string WalletNameEntryPlaceholder {
            get {
                return ResourceManager.GetString("WalletNameEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string MnemonicPhraseStepLabel {
            get {
                return ResourceManager.GetString("MnemonicPhraseStepLabel", resourceCulture);
            }
        }
        
        internal static string MnemonicDescriptionText {
            get {
                return ResourceManager.GetString("MnemonicDescriptionText", resourceCulture);
            }
        }
        
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        internal static string WordCountLabel {
            get {
                return ResourceManager.GetString("WordCountLabel", resourceCulture);
            }
        }
        
        internal static string MnemonicPhraseLabel {
            get {
                return ResourceManager.GetString("MnemonicPhraseLabel", resourceCulture);
            }
        }
        
        internal static string GenerateButton {
            get {
                return ResourceManager.GetString("GenerateButton", resourceCulture);
            }
        }
        
        internal static string LoseMnemonicPhraseText {
            get {
                return ResourceManager.GetString("LoseMnemonicPhraseText", resourceCulture);
            }
        }
        
        internal static string EnterMnemonicPhraseLabel {
            get {
                return ResourceManager.GetString("EnterMnemonicPhraseLabel", resourceCulture);
            }
        }
        
        internal static string EnterMnemonicPhraseEditorPlaceholder {
            get {
                return ResourceManager.GetString("EnterMnemonicPhraseEditorPlaceholder", resourceCulture);
            }
        }
        
        internal static string DerivedPasswordStepLabel {
            get {
                return ResourceManager.GetString("DerivedPasswordStepLabel", resourceCulture);
            }
        }
        
        internal static string DerivedPasswordDescriptionText {
            get {
                return ResourceManager.GetString("DerivedPasswordDescriptionText", resourceCulture);
            }
        }
        
        internal static string MnemonicVerificationStepLabel {
            get {
                return ResourceManager.GetString("MnemonicVerificationStepLabel", resourceCulture);
            }
        }
        
        internal static string MnemonicVerificationDescriptionText {
            get {
                return ResourceManager.GetString("MnemonicVerificationDescriptionText", resourceCulture);
            }
        }
        
        internal static string DerivedVerificationDescriptionText {
            get {
                return ResourceManager.GetString("DerivedVerificationDescriptionText", resourceCulture);
            }
        }
        
        internal static string EnterDerivedPasswordText {
            get {
                return ResourceManager.GetString("EnterDerivedPasswordText", resourceCulture);
            }
        }
        
        internal static string StoragePasswordStepLabel {
            get {
                return ResourceManager.GetString("StoragePasswordStepLabel", resourceCulture);
            }
        }
        
        internal static string StoragePasswordDescriptionText {
            get {
                return ResourceManager.GetString("StoragePasswordDescriptionText", resourceCulture);
            }
        }
        
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        internal static string WrongWordOrder {
            get {
                return ResourceManager.GetString("WrongWordOrder", resourceCulture);
            }
        }
        
        internal static string UseDerivedKeyPswd {
            get {
                return ResourceManager.GetString("UseDerivedKeyPswd", resourceCulture);
            }
        }
        
        internal static string PortfolioPageTitle {
            get {
                return ResourceManager.GetString("PortfolioPageTitle", resourceCulture);
            }
        }
        
        internal static string MainWalletLabel {
            get {
                return ResourceManager.GetString("MainWalletLabel", resourceCulture);
            }
        }
        
        internal static string WalletsPageTitle {
            get {
                return ResourceManager.GetString("WalletsPageTitle", resourceCulture);
            }
        }
        
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        internal static string ReceiveButton {
            get {
                return ResourceManager.GetString("ReceiveButton", resourceCulture);
            }
        }
        
        internal static string ConvertButton {
            get {
                return ResourceManager.GetString("ConvertButton", resourceCulture);
            }
        }
        
        internal static string DelegateButton {
            get {
                return ResourceManager.GetString("DelegateButton", resourceCulture);
            }
        }
        
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        internal static string BalanceUpdatingLabel {
            get {
                return ResourceManager.GetString("BalanceUpdatingLabel", resourceCulture);
            }
        }
        
        internal static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        internal static string NoTransactionsLabel {
            get {
                return ResourceManager.GetString("NoTransactionsLabel", resourceCulture);
            }
        }
        
        internal static string TransactionInfoPageTitle {
            get {
                return ResourceManager.GetString("TransactionInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string TransactionInfo {
            get {
                return ResourceManager.GetString("TransactionInfo", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        internal static string ShowInExplorerButton {
            get {
                return ResourceManager.GetString("ShowInExplorerButton", resourceCulture);
            }
        }
        
        internal static string TxSent {
            get {
                return ResourceManager.GetString("TxSent", resourceCulture);
            }
        }
        
        internal static string TxReceived {
            get {
                return ResourceManager.GetString("TxReceived", resourceCulture);
            }
        }
        
        internal static string TxSwapPayment {
            get {
                return ResourceManager.GetString("TxSwapPayment", resourceCulture);
            }
        }
        
        internal static string TxSwapRedeem {
            get {
                return ResourceManager.GetString("TxSwapRedeem", resourceCulture);
            }
        }
        
        internal static string TxSwapRefund {
            get {
                return ResourceManager.GetString("TxSwapRefund", resourceCulture);
            }
        }
        
        internal static string TxUnknown {
            get {
                return ResourceManager.GetString("TxUnknown", resourceCulture);
            }
        }
        
        internal static string SendPageTitle {
            get {
                return ResourceManager.GetString("SendPageTitle", resourceCulture);
            }
        }
        
        internal static string ScanningQrCodePageTitle {
            get {
                return ResourceManager.GetString("ScanningQrCodePageTitle", resourceCulture);
            }
        }
        
        internal static string PasteButton {
            get {
                return ResourceManager.GetString("PasteButton", resourceCulture);
            }
        }
        
        internal static string GasPriceLabel {
            get {
                return ResourceManager.GetString("GasPriceLabel", resourceCulture);
            }
        }
        
        internal static string GasLimitLabel {
            get {
                return ResourceManager.GetString("GasLimitLabel", resourceCulture);
            }
        }
        
        internal static string GasUsedLabel {
            get {
                return ResourceManager.GetString("GasUsedLabel", resourceCulture);
            }
        }
        
        internal static string IsInternalLabel {
            get {
                return ResourceManager.GetString("IsInternalLabel", resourceCulture);
            }
        }
        
        internal static string ConfirmTransactionLabel {
            get {
                return ResourceManager.GetString("ConfirmTransactionLabel", resourceCulture);
            }
        }
        
        internal static string ReceivePageTitle {
            get {
                return ResourceManager.GetString("ReceivePageTitle", resourceCulture);
            }
        }
        
        internal static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        internal static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        internal static string ShareButton {
            get {
                return ResourceManager.GetString("ShareButton", resourceCulture);
            }
        }
        
        internal static string DelegationListPageTitle {
            get {
                return ResourceManager.GetString("DelegationListPageTitle", resourceCulture);
            }
        }
        
        internal static string NoDelegationsLabel {
            get {
                return ResourceManager.GetString("NoDelegationsLabel", resourceCulture);
            }
        }
        
        internal static string NotDelegated {
            get {
                return ResourceManager.GetString("NotDelegated", resourceCulture);
            }
        }
        
        internal static string BakerListPageTitle {
            get {
                return ResourceManager.GetString("BakerListPageTitle", resourceCulture);
            }
        }
        
        internal static string SearchBarPlaceholder {
            get {
                return ResourceManager.GetString("SearchBarPlaceholder", resourceCulture);
            }
        }
        
        internal static string DelegatePageTitle {
            get {
                return ResourceManager.GetString("DelegatePageTitle", resourceCulture);
            }
        }
        
        internal static string DelegateToBakeryLabel {
            get {
                return ResourceManager.GetString("DelegateToBakeryLabel", resourceCulture);
            }
        }
        
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        internal static string ToAddressLabel {
            get {
                return ResourceManager.GetString("ToAddressLabel", resourceCulture);
            }
        }
        
        internal static string FromAddressLabel {
            get {
                return ResourceManager.GetString("FromAddressLabel", resourceCulture);
            }
        }
        
        internal static string BakerAddressPlaceholder {
            get {
                return ResourceManager.GetString("BakerAddressPlaceholder", resourceCulture);
            }
        }
        
        internal static string CustomBaker {
            get {
                return ResourceManager.GetString("CustomBaker", resourceCulture);
            }
        }
        
        internal static string WantToDelegate {
            get {
                return ResourceManager.GetString("WantToDelegate", resourceCulture);
            }
        }
        
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        internal static string CopyAndExitButton {
            get {
                return ResourceManager.GetString("CopyAndExitButton", resourceCulture);
            }
        }
        
        internal static string DelegationInfoPageTitle {
            get {
                return ResourceManager.GetString("DelegationInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string CheckRewardsButton {
            get {
                return ResourceManager.GetString("CheckRewardsButton", resourceCulture);
            }
        }
        
        internal static string ChangeBakerButton {
            get {
                return ResourceManager.GetString("ChangeBakerButton", resourceCulture);
            }
        }
        
        internal static string DelegateLabel {
            get {
                return ResourceManager.GetString("DelegateLabel", resourceCulture);
            }
        }
        
        internal static string Roi {
            get {
                return ResourceManager.GetString("Roi", resourceCulture);
            }
        }
        
        internal static string DelegationStatus {
            get {
                return ResourceManager.GetString("DelegationStatus", resourceCulture);
            }
        }
        
        internal static string DelegationTime {
            get {
                return ResourceManager.GetString("DelegationTime", resourceCulture);
            }
        }
        
        internal static string AccountSection {
            get {
                return ResourceManager.GetString("AccountSection", resourceCulture);
            }
        }
        
        internal static string BakerSection {
            get {
                return ResourceManager.GetString("BakerSection", resourceCulture);
            }
        }
        
        internal static string MoreSection {
            get {
                return ResourceManager.GetString("MoreSection", resourceCulture);
            }
        }
        
        internal static string SwapInfoPageTitle {
            get {
                return ResourceManager.GetString("SwapInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string SwapInfoLabel {
            get {
                return ResourceManager.GetString("SwapInfoLabel", resourceCulture);
            }
        }
        
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        internal static string SwapListPageTitle {
            get {
                return ResourceManager.GetString("SwapListPageTitle", resourceCulture);
            }
        }
        
        internal static string CreateSwapPageTitle {
            get {
                return ResourceManager.GetString("CreateSwapPageTitle", resourceCulture);
            }
        }
        
        internal static string SelectCurrenciesLabel {
            get {
                return ResourceManager.GetString("SelectCurrenciesLabel", resourceCulture);
            }
        }
        
        internal static string SwapFrom {
            get {
                return ResourceManager.GetString("SwapFrom", resourceCulture);
            }
        }
        
        internal static string SwapTo {
            get {
                return ResourceManager.GetString("SwapTo", resourceCulture);
            }
        }
        
        internal static string EstimatedPriceLabel {
            get {
                return ResourceManager.GetString("EstimatedPriceLabel", resourceCulture);
            }
        }
        
        internal static string EstimatedNetworkFeeLabel {
            get {
                return ResourceManager.GetString("EstimatedNetworkFeeLabel", resourceCulture);
            }
        }
        
        internal static string EnterAmountLabel {
            get {
                return ResourceManager.GetString("EnterAmountLabel", resourceCulture);
            }
        }
        
        internal static string AvailableMarketVolumeLabel {
            get {
                return ResourceManager.GetString("AvailableMarketVolumeLabel", resourceCulture);
            }
        }
        
        internal static string NoLiquidityLabel {
            get {
                return ResourceManager.GetString("NoLiquidityLabel", resourceCulture);
            }
        }
        
        internal static string PaymentFeeLabel {
            get {
                return ResourceManager.GetString("PaymentFeeLabel", resourceCulture);
            }
        }
        
        internal static string RedeemFeeLabel {
            get {
                return ResourceManager.GetString("RedeemFeeLabel", resourceCulture);
            }
        }
        
        internal static string MakerFeeLabel {
            get {
                return ResourceManager.GetString("MakerFeeLabel", resourceCulture);
            }
        }
        
        internal static string RewardForRedeemLabel {
            get {
                return ResourceManager.GetString("RewardForRedeemLabel", resourceCulture);
            }
        }
        
        internal static string TotalNetworkFeeLabel {
            get {
                return ResourceManager.GetString("TotalNetworkFeeLabel", resourceCulture);
            }
        }
        
        internal static string NoSwapsLabel {
            get {
                return ResourceManager.GetString("NoSwapsLabel", resourceCulture);
            }
        }
        
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        internal static string CreateSwapButton {
            get {
                return ResourceManager.GetString("CreateSwapButton", resourceCulture);
            }
        }
        
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string PeriodInactivePageTitle {
            get {
                return ResourceManager.GetString("PeriodInactivePageTitle", resourceCulture);
            }
        }
        
        internal static string BalanceUpdateIntervalPageTitle {
            get {
                return ResourceManager.GetString("BalanceUpdateIntervalPageTitle", resourceCulture);
            }
        }
        
        internal static string AutomaticSignOutLabel {
            get {
                return ResourceManager.GetString("AutomaticSignOutLabel", resourceCulture);
            }
        }
        
        internal static string PeriodOfInactiveLabel {
            get {
                return ResourceManager.GetString("PeriodOfInactiveLabel", resourceCulture);
            }
        }
        
        internal static string UseBiometricLabel {
            get {
                return ResourceManager.GetString("UseBiometricLabel", resourceCulture);
            }
        }
        
        internal static string DeletingWallet {
            get {
                return ResourceManager.GetString("DeletingWallet", resourceCulture);
            }
        }
        
        internal static string DeletingWalletText {
            get {
                return ResourceManager.GetString("DeletingWalletText", resourceCulture);
            }
        }
        
        internal static string DeletingWalletConfirmationText {
            get {
                return ResourceManager.GetString("DeletingWalletConfirmationText", resourceCulture);
            }
        }
        
        internal static string SecuritySection {
            get {
                return ResourceManager.GetString("SecuritySection", resourceCulture);
            }
        }
        
        internal static string CommunitySection {
            get {
                return ResourceManager.GetString("CommunitySection", resourceCulture);
            }
        }
        
        internal static string WalletsSection {
            get {
                return ResourceManager.GetString("WalletsSection", resourceCulture);
            }
        }
        
        internal static string CommonSection {
            get {
                return ResourceManager.GetString("CommonSection", resourceCulture);
            }
        }
        
        internal static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
        
        internal static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        internal static string PortfolioTab {
            get {
                return ResourceManager.GetString("PortfolioTab", resourceCulture);
            }
        }
        
        internal static string WalletsTab {
            get {
                return ResourceManager.GetString("WalletsTab", resourceCulture);
            }
        }
        
        internal static string ConversionTab {
            get {
                return ResourceManager.GetString("ConversionTab", resourceCulture);
            }
        }
        
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        internal static string EnableBiometricLabel {
            get {
                return ResourceManager.GetString("EnableBiometricLabel", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        internal static string SuccessDelegation {
            get {
                return ResourceManager.GetString("SuccessDelegation", resourceCulture);
            }
        }
        
        internal static string DelegationListWillBeUpdated {
            get {
                return ResourceManager.GetString("DelegationListWillBeUpdated", resourceCulture);
            }
        }
        
        internal static string ExplorerUri {
            get {
                return ResourceManager.GetString("ExplorerUri", resourceCulture);
            }
        }
        
        internal static string sentTo {
            get {
                return ResourceManager.GetString("sentTo", resourceCulture);
            }
        }
        
        internal static string isNotInWordlist {
            get {
                return ResourceManager.GetString("isNotInWordlist", resourceCulture);
            }
        }
        
        internal static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        internal static string TransactionIdCopied {
            get {
                return ResourceManager.GetString("TransactionIdCopied", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        internal static string PasswordHasInsufficientComplexity {
            get {
                return ResourceManager.GetString("PasswordHasInsufficientComplexity", resourceCulture);
            }
        }
        
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        internal static string InvalidMnemonic {
            get {
                return ResourceManager.GetString("InvalidMnemonic", resourceCulture);
            }
        }
        
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        internal static string InsufficientChainFunds {
            get {
                return ResourceManager.GetString("InsufficientChainFunds", resourceCulture);
            }
        }
        
        internal static string SufficientNetworkFee {
            get {
                return ResourceManager.GetString("SufficientNetworkFee", resourceCulture);
            }
        }
        
        internal static string TooHighNetworkFee {
            get {
                return ResourceManager.GetString("TooHighNetworkFee", resourceCulture);
            }
        }
        
        internal static string TotalNetworkFeeDetail {
            get {
                return ResourceManager.GetString("TotalNetworkFeeDetail", resourceCulture);
            }
        }
        
        internal static string LowFees {
            get {
                return ResourceManager.GetString("LowFees", resourceCulture);
            }
        }
        
        internal static string NetworkFee {
            get {
                return ResourceManager.GetString("NetworkFee", resourceCulture);
            }
        }
        
        internal static string FailedToSend {
            get {
                return ResourceManager.GetString("FailedToSend", resourceCulture);
            }
        }
        
        internal static string FailedToConvert {
            get {
                return ResourceManager.GetString("FailedToConvert", resourceCulture);
            }
        }
        
        internal static string PriceChanged {
            get {
                return ResourceManager.GetString("PriceChanged", resourceCulture);
            }
        }
        
        internal static string SwapCreated {
            get {
                return ResourceManager.GetString("SwapCreated", resourceCulture);
            }
        }
        
        internal static string GenerateMnemonic {
            get {
                return ResourceManager.GetString("GenerateMnemonic", resourceCulture);
            }
        }
        
        internal static string EmptyClipboard {
            get {
                return ResourceManager.GetString("EmptyClipboard", resourceCulture);
            }
        }
        
        internal static string EmptyWalletName {
            get {
                return ResourceManager.GetString("EmptyWalletName", resourceCulture);
            }
        }
        
        internal static string InvalidWalletName {
            get {
                return ResourceManager.GetString("InvalidWalletName", resourceCulture);
            }
        }
        
        internal static string WalletAlreadyExists {
            get {
                return ResourceManager.GetString("WalletAlreadyExists", resourceCulture);
            }
        }
        
        internal static string BakerIsDeactivated {
            get {
                return ResourceManager.GetString("BakerIsDeactivated", resourceCulture);
            }
        }
        
        internal static string AlreadyDelegatedFrom {
            get {
                return ResourceManager.GetString("AlreadyDelegatedFrom", resourceCulture);
            }
        }
        
        internal static string AutofillTransactionFailed {
            get {
                return ResourceManager.GetString("AutofillTransactionFailed", resourceCulture);
            }
        }
        
        internal static string SuccessfulCheck {
            get {
                return ResourceManager.GetString("SuccessfulCheck", resourceCulture);
            }
        }
        
        internal static string AddressSharing {
            get {
                return ResourceManager.GetString("AddressSharing", resourceCulture);
            }
        }
        
        internal static string MyPublicAddress {
            get {
                return ResourceManager.GetString("MyPublicAddress", resourceCulture);
            }
        }
        
        internal static string HasBeenUpdated {
            get {
                return ResourceManager.GetString("HasBeenUpdated", resourceCulture);
            }
        }
        
        internal static string AddressCopied {
            get {
                return ResourceManager.GetString("AddressCopied", resourceCulture);
            }
        }
        
        internal static string CopyError {
            get {
                return ResourceManager.GetString("CopyError", resourceCulture);
            }
        }
        
        internal static string CreateWalletError {
            get {
                return ResourceManager.GetString("CreateWalletError", resourceCulture);
            }
        }
        
        internal static string EmptyAddressError {
            get {
                return ResourceManager.GetString("EmptyAddressError", resourceCulture);
            }
        }
        
        internal static string InvalidAddressError {
            get {
                return ResourceManager.GetString("InvalidAddressError", resourceCulture);
            }
        }
        
        internal static string CommissionLessThanZeroError {
            get {
                return ResourceManager.GetString("CommissionLessThanZeroError", resourceCulture);
            }
        }
        
        internal static string SendingTransactionError {
            get {
                return ResourceManager.GetString("SendingTransactionError", resourceCulture);
            }
        }
        
        internal static string DelegationError {
            get {
                return ResourceManager.GetString("DelegationError", resourceCulture);
            }
        }
        
        internal static string DelegationValidationError {
            get {
                return ResourceManager.GetString("DelegationValidationError", resourceCulture);
            }
        }
        
        internal static string NoTezosError {
            get {
                return ResourceManager.GetString("NoTezosError", resourceCulture);
            }
        }
        
        internal static string AmountLessThanZeroError {
            get {
                return ResourceManager.GetString("AmountLessThanZeroError", resourceCulture);
            }
        }
        
        internal static string NoLiquidityError {
            get {
                return ResourceManager.GetString("NoLiquidityError", resourceCulture);
            }
        }
        
        internal static string PriceChangedError {
            get {
                return ResourceManager.GetString("PriceChangedError", resourceCulture);
            }
        }
        
        internal static string OrderRejectedError {
            get {
                return ResourceManager.GetString("OrderRejectedError", resourceCulture);
            }
        }
        
        internal static string TimeoutReachedError {
            get {
                return ResourceManager.GetString("TimeoutReachedError", resourceCulture);
            }
        }
        
        internal static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        internal static string AvailableFundsError {
            get {
                return ResourceManager.GetString("AvailableFundsError", resourceCulture);
            }
        }
        
        internal static string EmptyMnemonicError {
            get {
                return ResourceManager.GetString("EmptyMnemonicError", resourceCulture);
            }
        }
        
        internal static string MnemonicWordCountError {
            get {
                return ResourceManager.GetString("MnemonicWordCountError", resourceCulture);
            }
        }
        
        internal static string WrongDelegationAddressError {
            get {
                return ResourceManager.GetString("WrongDelegationAddressError", resourceCulture);
            }
        }
        
        internal static string DelegationLimitWarning {
            get {
                return ResourceManager.GetString("DelegationLimitWarning", resourceCulture);
            }
        }
        
        internal static string BakerIsOverdelegatedWarning {
            get {
                return ResourceManager.GetString("BakerIsOverdelegatedWarning", resourceCulture);
            }
        }
        
        internal static string RemoveTxWarning {
            get {
                return ResourceManager.GetString("RemoveTxWarning", resourceCulture);
            }
        }
        
        internal static string UpdateApp {
            get {
                return ResourceManager.GetString("UpdateApp", resourceCulture);
            }
        }
        
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NotSupportSecureStorage {
            get {
                return ResourceManager.GetString("NotSupportSecureStorage", resourceCulture);
            }
        }
        
        internal static string NeedPermissionsForBiometricLogin {
            get {
                return ResourceManager.GetString("NeedPermissionsForBiometricLogin", resourceCulture);
            }
        }
        
        internal static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        internal static string SorryLabel {
            get {
                return ResourceManager.GetString("SorryLabel", resourceCulture);
            }
        }
        
        internal static string ImpossibleEnableBiometric {
            get {
                return ResourceManager.GetString("ImpossibleEnableBiometric", resourceCulture);
            }
        }
        
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        internal static string SwapHistoryText {
            get {
                return ResourceManager.GetString("SwapHistoryText", resourceCulture);
            }
        }
    }
}
