//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




namespace namespace namespace namespace atomexatomex..atomex.Resourcesatomex.ResourcesResourcesResources {
 {
 {
 {
    using using using using SystemSystemSystemSystem;
    using System.Reflection;
    
;
    using System.Reflection;
    
;
    using System.Reflection;
    
;
    using System.Reflection;
    
    
    
    
    
    [[[[System.CodeDom.Compiler.GeneratedCodeAttribute(System.CodeDom.Compiler.GeneratedCodeAttribute(System.CodeDom.Compiler.GeneratedCodeAttribute(System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")"System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")"System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")"System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    ]
    []
    ][System.Diagnostics.DebuggerNonUserCodeAttribute([System.Diagnostics.DebuggerNonUserCodeAttribute(
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    )]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    )]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class internal class internal class internal class AppResources_frAppResources_trAppResourcesAppResources_ru {
     {
     {
     {
        
        
        
        
        private private private private static static static static System.Resources.ResourceManagerSystem.Resources.ResourceManager System.Resources.ResourceManager  System.Resources.ResourceManagerresourceManresourceMan;
        ;
        resourceMan resourceMan;
        ;
        
        
        private static System.Globalization.CultureInfo resourceCulture;
        private static System.Globalization.CultureInfo resourceCulture;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        
        
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttributec static static Syst        ("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal internal AppResources_trAppResources_tr((AppResources_trAppResources_tr(()))) {
         {
         {
             {
        }
        }
        }
    }
    
    
    
    
    [System.ComponentModel.EditorBrowsableAttribute([System.ComponentModel.EditorBrowsableAttribute([System.ComponentModel.EditorBrowsableAttribute([System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableStateSystem.ComponentModel.EditorBrowsableState..AdvancedSystem.ComponentModel.EditorBrowsableState.AdvancedSystem.ComponentModel.EditorBrowsableState.Advanced)]
    )]
    )]
    Advanced)]
    internal internal internal internal static static static System.Resources.ResourceManager static System.Resources.ResourceManager ResourceManager {
    System.Resources.ResourceManagerSystem.Resources.ResourceManager ResourceManager {
     ResourceManager {
    ResourceManager {
            get {
            get {
            get {
            get {
                if (if (if (if (object.object.object.object.EqualsEqualsEqualsEquals((((null, resourceMannull, resourceMannull, resourceMannull, resourceMan)))))) {
             {
             {
                )) {
                        System.Resources.ResourceManager tempSystem.Resources.ResourceManager temp =  = System.Resources.ResourceManager tempSystem.Resources.ResourceManager temp =  = new new new new System.Resources.ResourceManagerSystem.Resources.ResourceManager(System.Resources.ResourceManagerSystem.Resources.ResourceManager((("atomex.Resources.AppResources.tr", "atomex.Resources.AppResources.fr", "atomex.Resources.AppResources.ru", "atomex.Resources.AppResources", typeof(typeof(typeof(typeof(AppResources_trAppResources_fr).).AssemblyAppResources));
                                    AppResources_ru).Assembly);
                                .Assembly);
                            Assembly);
                        resourceMan = resourceMan = resourceMan = resourceMan = temptemp;
                        ;
                        temp;
                        temp;
                    }
                    }
                    }
                    }
                    return return return return resourceManresourceMan;
                    ;
                    resourceMan;
                    resourceMan;
                }
                }
                }
                }
            }
            }
            }
            }
            
            [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
            internal static System.Globalization.CultureInfo Culture {
                get {
                    return resourceCulture;
                }
                
                [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
                internal static System.Globalization.CultureInfo
                [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
                internal static System.Globalization.CultureInfo Culture {
                    get {
                        return resourceCulture;
                    }
                    
                    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
                    internal static System.Globalization.CultureInfo Culture {
                        get {
                            return resourceCulture;
                        }
                        set {
                        set {
                         Culture {
                            get {
                                return resourceCulture;
                            }
                            set {
                            set {
                                resourceCulture = resourceCulture = resourceCulture = resourceCulture = value;
                                                  valuevaluesa;
                                ;
            value;
                            }
                        }
                        
                        internal static }
                        }
                        
                        internal static string AcceptButton {
                            get {
                                return ResourceManager.GetString("AcceptButton", resourceCulture}
                }
                
                internal static string AcceptButton {
                    get {
                        return ResourceManager.GetString("AcceptButton", resourceCulture}
                        }
                        
                        internal static string AcceptButton {
                            get {
                                return ResourceManager.GetString("AcceptButton", resourceCulture);
                            }
                        }
                        
                        internal static string CancelButton {
                            get {
                                return ResourceManager.GetString("CancelButton", resourceCulture);
                            }
                        }
                        
                        internal static string NextButton {
                            get {
                                return ResourceManager.GetString("NextButton", resourceCulture);
                            }
                        }
                        
                        internal static string ConfirmButton {
                            get {
                                return ResourceManager.GetString("ConfirmButton", resourceCulture);
                            }
                        }
                        
                        internal static string ReviewButton {
                            get {
                                return ResourceManager.GetString("ReviewButton", resourceCulture);
                            }
                        }
                        
                        internal static string HideButton {
                            get {
                                return ResourceManager.GetString("HideButton", resourceCulture);
                            }
                        }
                        
                        internal static string UnderstandButton {
                            get {
                                return ResourceManager.GetString("UnderstandButton", resourceCulture);
                            }
                        }
                        
                        internal static string DeleteButton {
                            get {
                                return ResourceManager.GetString("DeleteButton", resourceCulture);
                            }
                        }
                        
                        internal static string RemoveButton {
                            get {
                                return ResourceManager.GetString("RemoveButton", resourceCulture);
                            }
                        }
                        
                        internal static string CloseButton {
                            get {
                                return ResourceManager.GetString("CloseButton", resourceCulture);
                            }
                        }
                        
                        internal static string MainNetButton {
                            get {
                                return ResourceManager.GetString("MainNetButton", resourceCulture);
                            }
                        }
                        
                        internal static string TestNetButton {
                            get {
                                return ResourceManager.GetString("TestNetButton", resourceCulture);
                            }
                        }
                        
                        internal static string PasswordEntryPlaceholder {
                            get {
                                return ResourceManager.GetString("PasswordEntryPlaceholder", resourceCulture);
                            }
                        }
                        
                        internal static string PasswordConfirmationEntryPlaceholder {
                            get {
                                return ResourceManager.GetString("PasswordConfirmationEntryPlaceholder", resourceCulture);
                            }
                        }
                        
                        internal static string AddressEntryPlaceholder {
                            get {
                                return ResourceManager.GetString("AddressEntryPlaceholder", resourceCulture);
                            }
                        }
                        
                        internal static string AmountEntryPlaceholder {
                            get {
                                return ResourceManager.GetString("AmountEntryPlaceholder", resourceCulture);
                            }
                        }
                        
                        internal static string );
                     {
                        get {
                            return }
                        ResourceManager.}
etString{                    ("UseDefaultFeeLabel", resourceCulture
;
                }
            }
            
            internal static internal static string FeeLabel {
                get {
                    return ResourceManager.GetString("FeeLabel", resourceCulturel stat );
                }
            }
            
            internal CancelButton        {
              string  rceMan get {
RateLabelA                     {
                        get {
                                urn                  GetString(eturn "FeeRateLabel", resourceCulture);
                               R
sourceManager                         .    }
                            
        GetStringintrrnal tring("AmountEntryPlaceholder", resourceCulture);
                            }
                        }
                        
                        internal static string );
                     {
                        get {
                            return }
                        ResourceManager.}
etString{                    ("UseDefaultFeeLabel", resourceCulture
;
                }
            }
            
            internal static internal static string FeeLabel {
                get {
                    return ResourceManager.GetString("FeeLabel", resourceCulturel stat );
                }
            }
            
            internal CancelButton        {
              string  rceMan get {
RateLabelA                     {
                        get {
                                urn                  GetString(eturn "FeeRateLabel", resourceCulture);
                               R
sourceManager                         .    }
                            
        GetStringintstring ConfirmationLabel {
                        get {
                            return (ResourceManager.GetString("ConfirmationLabel", resourceCulture);
                            }
                        }
                        
                        internal static "CancelButton"string , AmountLabel {
                                 get  {            resourceCulturereturn );
GetString                            ("AmountLabel", resourceCulture);
                                    } 
       }     }
               
       
            inte        internal static string string MinimumAmountLabel {
                 extButton get                        {  getreturn  {
                                  return (ResourceManager.GetString"MinimumAmountLabel" , resourceCulture);
                              
                         }
                              
esourceCulture                     )       
        internal             static }
            }
            
            string internal n