//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atomex.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("atomex.Resources.AppResources_ru", typeof(AppResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        internal static string ReviewButton {
            get {
                return ResourceManager.GetString("ReviewButton", resourceCulture);
            }
        }
        
        internal static string HideButton {
            get {
                return ResourceManager.GetString("HideButton", resourceCulture);
            }
        }
        
        internal static string UnderstandButton {
            get {
                return ResourceManager.GetString("UnderstandButton", resourceCulture);
            }
        }
        
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        internal static string MainNetButton {
            get {
                return ResourceManager.GetString("MainNetButton", resourceCulture);
            }
        }
        
        internal static string TestNetButton {
            get {
                return ResourceManager.GetString("TestNetButton", resourceCulture);
            }
        }
        
        internal static string PasswordEntryPlaceholder {
            get {
                return ResourceManager.GetString("PasswordEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string PasswordConfirmationEntryPlaceholder {
            get {
                return ResourceManager.GetString("PasswordConfirmationEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string AddressEntryPlaceholder {
            get {
                return ResourceManager.GetString("AddressEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string AmountEntryPlaceholder {
            get {
                return ResourceManager.GetString("AmountEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string UseDefaultFeeLabel {
            get {
                return ResourceManager.GetString("UseDefaultFeeLabel", resourceCulture);
            }
        }
        
        internal static string FeeLabel {
            get {
                return ResourceManager.GetString("FeeLabel", resourceCulture);
            }
        }
        
        internal static string FeeRateLabel {
            get {
                return ResourceManager.GetString("FeeRateLabel", resourceCulture);
            }
        }
        
        internal static string ConfirmationLabel {
            get {
                return ResourceManager.GetString("ConfirmationLabel", resourceCulture);
            }
        }
        
        internal static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        internal static string MinimumAmountLabel {
            get {
                return ResourceManager.GetString("MinimumAmountLabel", resourceCulture);
            }
        }
        
        internal static string TotalAmountInclFees {
            get {
                return ResourceManager.GetString("TotalAmountInclFees", resourceCulture);
            }
        }
        
        internal static string TransactionTime {
            get {
                return ResourceManager.GetString("TransactionTime", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string MinLabel {
            get {
                return ResourceManager.GetString("MinLabel", resourceCulture);
            }
        }
        
        internal static string MaxButton {
            get {
                return ResourceManager.GetString("MaxButton", resourceCulture);
            }
        }
        
        internal static string IdLabel {
            get {
                return ResourceManager.GetString("IdLabel", resourceCulture);
            }
        }
        
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        internal static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        internal static string PasteButton {
            get {
                return ResourceManager.GetString("PasteButton", resourceCulture);
            }
        }
        
        internal static string GasPriceLabel {
            get {
                return ResourceManager.GetString("GasPriceLabel", resourceCulture);
            }
        }
        
        internal static string GasLimitLabel {
            get {
                return ResourceManager.GetString("GasLimitLabel", resourceCulture);
            }
        }
        
        internal static string GasUsedLabel {
            get {
                return ResourceManager.GetString("GasUsedLabel", resourceCulture);
            }
        }
        
        internal static string IsInternalLabel {
            get {
                return ResourceManager.GetString("IsInternalLabel", resourceCulture);
            }
        }
        
        internal static string MyWalletsButton {
            get {
                return ResourceManager.GetString("MyWalletsButton", resourceCulture);
            }
        }
        
        internal static string CreateNewWalletButton {
            get {
                return ResourceManager.GetString("CreateNewWalletButton", resourceCulture);
            }
        }
        
        internal static string RestoreWalletButton {
            get {
                return ResourceManager.GetString("RestoreWalletButton", resourceCulture);
            }
        }
        
        internal static string SelectWalletLabel {
            get {
                return ResourceManager.GetString("SelectWalletLabel", resourceCulture);
            }
        }
        
        internal static string MyWalletsTitle {
            get {
                return ResourceManager.GetString("MyWalletsTitle", resourceCulture);
            }
        }
        
        internal static string UnlockTitle {
            get {
                return ResourceManager.GetString("UnlockTitle", resourceCulture);
            }
        }
        
        internal static string UnlockLabel {
            get {
                return ResourceManager.GetString("UnlockLabel", resourceCulture);
            }
        }
        
        internal static string UnlockButton {
            get {
                return ResourceManager.GetString("UnlockButton", resourceCulture);
            }
        }
        
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        internal static string UseBiometric {
            get {
                return ResourceManager.GetString("UseBiometric", resourceCulture);
            }
        }
        
        internal static string CreatePin {
            get {
                return ResourceManager.GetString("CreatePin", resourceCulture);
            }
        }
        
        internal static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        internal static string ReEnterPin {
            get {
                return ResourceManager.GetString("ReEnterPin", resourceCulture);
            }
        }
        
        internal static string SetPinIsteadOfPswd {
            get {
                return ResourceManager.GetString("SetPinIsteadOfPswd", resourceCulture);
            }
        }
        
        internal static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        internal static string AttemptsLeft {
            get {
                return ResourceManager.GetString("AttemptsLeft", resourceCulture);
            }
        }
        
        internal static string TryAgainInMinutes {
            get {
                return ResourceManager.GetString("TryAgainInMinutes", resourceCulture);
            }
        }
        
        internal static string WalletHasBeenLocked {
            get {
                return ResourceManager.GetString("WalletHasBeenLocked", resourceCulture);
            }
        }
        
        internal static string CreateNewWalletPageTitle {
            get {
                return ResourceManager.GetString("CreateNewWalletPageTitle", resourceCulture);
            }
        }
        
        internal static string RestoreWalletPageTitle {
            get {
                return ResourceManager.GetString("RestoreWalletPageTitle", resourceCulture);
            }
        }
        
        internal static string WalletTypeStepLabel {
            get {
                return ResourceManager.GetString("WalletTypeStepLabel", resourceCulture);
            }
        }
        
        internal static string SelectTypeLabel {
            get {
                return ResourceManager.GetString("SelectTypeLabel", resourceCulture);
            }
        }
        
        internal static string WalletNameStepLabel {
            get {
                return ResourceManager.GetString("WalletNameStepLabel", resourceCulture);
            }
        }
        
        internal static string EnterNameLabel {
            get {
                return ResourceManager.GetString("EnterNameLabel", resourceCulture);
            }
        }
        
        internal static string WalletNameEntryPlaceholder {
            get {
                return ResourceManager.GetString("WalletNameEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string MnemonicPhraseStepLabel {
            get {
                return ResourceManager.GetString("MnemonicPhraseStepLabel", resourceCulture);
            }
        }
        
        internal static string MnemonicDescriptionText {
            get {
                return ResourceManager.GetString("MnemonicDescriptionText", resourceCulture);
            }
        }
        
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        internal static string WordCountLabel {
            get {
                return ResourceManager.GetString("WordCountLabel", resourceCulture);
            }
        }
        
        internal static string GenerateButton {
            get {
                return ResourceManager.GetString("GenerateButton", resourceCulture);
            }
        }
        
        internal static string LoseMnemonicPhraseText {
            get {
                return ResourceManager.GetString("LoseMnemonicPhraseText", resourceCulture);
            }
        }
        
        internal static string EnterMnemonicPhraseLabel {
            get {
                return ResourceManager.GetString("EnterMnemonicPhraseLabel", resourceCulture);
            }
        }
        
        internal static string EnterMnemonicPhraseEditorPlaceholder {
            get {
                return ResourceManager.GetString("EnterMnemonicPhraseEditorPlaceholder", resourceCulture);
            }
        }
        
        internal static string DerivedPasswordStepLabel {
            get {
                return ResourceManager.GetString("DerivedPasswordStepLabel", resourceCulture);
            }
        }
        
        internal static string DerivedPasswordDescriptionText {
            get {
                return ResourceManager.GetString("DerivedPasswordDescriptionText", resourceCulture);
            }
        }
        
        internal static string MnemonicVerificationStepLabel {
            get {
                return ResourceManager.GetString("MnemonicVerificationStepLabel", resourceCulture);
            }
        }
        
        internal static string MnemonicVerificationDescriptionText {
            get {
                return ResourceManager.GetString("MnemonicVerificationDescriptionText", resourceCulture);
            }
        }
        
        internal static string DerivedVerificationDescriptionText {
            get {
                return ResourceManager.GetString("DerivedVerificationDescriptionText", resourceCulture);
            }
        }
        
        internal static string EnterDerivedPasswordText {
            get {
                return ResourceManager.GetString("EnterDerivedPasswordText", resourceCulture);
            }
        }
        
        internal static string StoragePasswordStepLabel {
            get {
                return ResourceManager.GetString("StoragePasswordStepLabel", resourceCulture);
            }
        }
        
        internal static string StoragePasswordDescriptionText {
            get {
                return ResourceManager.GetString("StoragePasswordDescriptionText", resourceCulture);
            }
        }
        
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        internal static string WrongWordOrder {
            get {
                return ResourceManager.GetString("WrongWordOrder", resourceCulture);
            }
        }
        
        internal static string UseDerivedKeyPswd {
            get {
                return ResourceManager.GetString("UseDerivedKeyPswd", resourceCulture);
            }
        }
        
        internal static string PortfolioPageTitle {
            get {
                return ResourceManager.GetString("PortfolioPageTitle", resourceCulture);
            }
        }
        
        internal static string MainWalletLabel {
            get {
                return ResourceManager.GetString("MainWalletLabel", resourceCulture);
            }
        }
        
        internal static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        internal static string CoinsAndTokens {
            get {
                return ResourceManager.GetString("CoinsAndTokens", resourceCulture);
            }
        }
        
        internal static string ManageAssets {
            get {
                return ResourceManager.GetString("ManageAssets", resourceCulture);
            }
        }
        
        internal static string AvailableToSpend {
            get {
                return ResourceManager.GetString("AvailableToSpend", resourceCulture);
            }
        }
        
        internal static string BalanceOnHold {
            get {
                return ResourceManager.GetString("BalanceOnHold", resourceCulture);
            }
        }
        
        internal static string RestoringWallet {
            get {
                return ResourceManager.GetString("RestoringWallet", resourceCulture);
            }
        }
        
        internal static string WalletsPageTitle {
            get {
                return ResourceManager.GetString("WalletsPageTitle", resourceCulture);
            }
        }
        
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        internal static string ReceiveButton {
            get {
                return ResourceManager.GetString("ReceiveButton", resourceCulture);
            }
        }
        
        internal static string BuyButton {
            get {
                return ResourceManager.GetString("BuyButton", resourceCulture);
            }
        }
        
        internal static string ConvertButton {
            get {
                return ResourceManager.GetString("ConvertButton", resourceCulture);
            }
        }
        
        internal static string DelegateButton {
            get {
                return ResourceManager.GetString("DelegateButton", resourceCulture);
            }
        }
        
        internal static string UndelegateButton {
            get {
                return ResourceManager.GetString("UndelegateButton", resourceCulture);
            }
        }
        
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        internal static string AvailableBalance {
            get {
                return ResourceManager.GetString("AvailableBalance", resourceCulture);
            }
        }
        
        internal static string BalanceUpdatingLabel {
            get {
                return ResourceManager.GetString("BalanceUpdatingLabel", resourceCulture);
            }
        }
        
        internal static string StillUpdatingBalances {
            get {
                return ResourceManager.GetString("StillUpdatingBalances", resourceCulture);
            }
        }
        
        internal static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        internal static string NoTransactionsLabel {
            get {
                return ResourceManager.GetString("NoTransactionsLabel", resourceCulture);
            }
        }
        
        internal static string UnconfirmedAmountLabel {
            get {
                return ResourceManager.GetString("UnconfirmedAmountLabel", resourceCulture);
            }
        }
        
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        internal static string Collectibles {
            get {
                return ResourceManager.GetString("Collectibles", resourceCulture);
            }
        }
        
        internal static string Delegations {
            get {
                return ResourceManager.GetString("Delegations", resourceCulture);
            }
        }
        
        internal static string AddressInfoPageTitle {
            get {
                return ResourceManager.GetString("AddressInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        internal static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        internal static string CurrencyAddresses {
            get {
                return ResourceManager.GetString("CurrencyAddresses", resourceCulture);
            }
        }
        
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        internal static string CopyPrivateKeyButton {
            get {
                return ResourceManager.GetString("CopyPrivateKeyButton", resourceCulture);
            }
        }
        
        internal static string CopyKeyButton {
            get {
                return ResourceManager.GetString("CopyKeyButton", resourceCulture);
            }
        }
        
        internal static string TransactionInfoPageTitle {
            get {
                return ResourceManager.GetString("TransactionInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string TransactionInfo {
            get {
                return ResourceManager.GetString("TransactionInfo", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        internal static string ShowInExplorerButton {
            get {
                return ResourceManager.GetString("ShowInExplorerButton", resourceCulture);
            }
        }
        
        internal static string TxSent {
            get {
                return ResourceManager.GetString("TxSent", resourceCulture);
            }
        }
        
        internal static string TxReceived {
            get {
                return ResourceManager.GetString("TxReceived", resourceCulture);
            }
        }
        
        internal static string TxSwapPayment {
            get {
                return ResourceManager.GetString("TxSwapPayment", resourceCulture);
            }
        }
        
        internal static string TxSwapRedeem {
            get {
                return ResourceManager.GetString("TxSwapRedeem", resourceCulture);
            }
        }
        
        internal static string TxSwapRefund {
            get {
                return ResourceManager.GetString("TxSwapRefund", resourceCulture);
            }
        }
        
        internal static string TxTokenCall {
            get {
                return ResourceManager.GetString("TxTokenCall", resourceCulture);
            }
        }
        
        internal static string TxSwapCall {
            get {
                return ResourceManager.GetString("TxSwapCall", resourceCulture);
            }
        }
        
        internal static string TxTokenApprove {
            get {
                return ResourceManager.GetString("TxTokenApprove", resourceCulture);
            }
        }
        
        internal static string TxUnknown {
            get {
                return ResourceManager.GetString("TxUnknown", resourceCulture);
            }
        }
        
        internal static string SendPageTitle {
            get {
                return ResourceManager.GetString("SendPageTitle", resourceCulture);
            }
        }
        
        internal static string ScanningQrCodePageTitle {
            get {
                return ResourceManager.GetString("ScanningQrCodePageTitle", resourceCulture);
            }
        }
        
        internal static string ScannerTopOverlayText {
            get {
                return ResourceManager.GetString("ScannerTopOverlayText", resourceCulture);
            }
        }
        
        internal static string ScannerBottomOverlayText {
            get {
                return ResourceManager.GetString("ScannerBottomOverlayText", resourceCulture);
            }
        }
        
        internal static string ConfirmTransactionLabel {
            get {
                return ResourceManager.GetString("ConfirmTransactionLabel", resourceCulture);
            }
        }
        
        internal static string SendFrom {
            get {
                return ResourceManager.GetString("SendFrom", resourceCulture);
            }
        }
        
        internal static string ReceiveTo {
            get {
                return ResourceManager.GetString("ReceiveTo", resourceCulture);
            }
        }
        
        internal static string ChooseAnAddress {
            get {
                return ResourceManager.GetString("ChooseAnAddress", resourceCulture);
            }
        }
        
        internal static string MyAddresses {
            get {
                return ResourceManager.GetString("MyAddresses", resourceCulture);
            }
        }
        
        internal static string SortByBalanceButton {
            get {
                return ResourceManager.GetString("SortByBalanceButton", resourceCulture);
            }
        }
        
        internal static string SortByDateButton {
            get {
                return ResourceManager.GetString("SortByDateButton", resourceCulture);
            }
        }
        
        internal static string ExternalAddress {
            get {
                return ResourceManager.GetString("ExternalAddress", resourceCulture);
            }
        }
        
        internal static string EnterAnExternalAddress {
            get {
                return ResourceManager.GetString("EnterAnExternalAddress", resourceCulture);
            }
        }
        
        internal static string SaveToMyAddresses {
            get {
                return ResourceManager.GetString("SaveToMyAddresses", resourceCulture);
            }
        }
        
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        internal static string SelectedOfTotal {
            get {
                return ResourceManager.GetString("SelectedOfTotal", resourceCulture);
            }
        }
        
        internal static string AddressesNotFound {
            get {
                return ResourceManager.GetString("AddressesNotFound", resourceCulture);
            }
        }
        
        internal static string EnterAddressPlaceholder {
            get {
                return ResourceManager.GetString("EnterAddressPlaceholder", resourceCulture);
            }
        }
        
        internal static string ReceivePageTitle {
            get {
                return ResourceManager.GetString("ReceivePageTitle", resourceCulture);
            }
        }
        
        internal static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        internal static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        internal static string ShareButton {
            get {
                return ResourceManager.GetString("ShareButton", resourceCulture);
            }
        }
        
        internal static string MyCurrencyAddresses {
            get {
                return ResourceManager.GetString("MyCurrencyAddresses", resourceCulture);
            }
        }
        
        internal static string ReceivingCurrencyAddress {
            get {
                return ResourceManager.GetString("ReceivingCurrencyAddress", resourceCulture);
            }
        }
        
        internal static string CopyAddress {
            get {
                return ResourceManager.GetString("CopyAddress", resourceCulture);
            }
        }
        
        internal static string DelegationListPageTitle {
            get {
                return ResourceManager.GetString("DelegationListPageTitle", resourceCulture);
            }
        }
        
        internal static string NoDelegationsLabel {
            get {
                return ResourceManager.GetString("NoDelegationsLabel", resourceCulture);
            }
        }
        
        internal static string NotDelegated {
            get {
                return ResourceManager.GetString("NotDelegated", resourceCulture);
            }
        }
        
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        internal static string EstimatedRoi {
            get {
                return ResourceManager.GetString("EstimatedRoi", resourceCulture);
            }
        }
        
        internal static string DelegatingTo {
            get {
                return ResourceManager.GetString("DelegatingTo", resourceCulture);
            }
        }
        
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        internal static string ToAddressLabel {
            get {
                return ResourceManager.GetString("ToAddressLabel", resourceCulture);
            }
        }
        
        internal static string FromAddressLabel {
            get {
                return ResourceManager.GetString("FromAddressLabel", resourceCulture);
            }
        }
        
        internal static string EnterBakerNamePlaceholder {
            get {
                return ResourceManager.GetString("EnterBakerNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string CustomBaker {
            get {
                return ResourceManager.GetString("CustomBaker", resourceCulture);
            }
        }
        
        internal static string FeeCalculationLabel {
            get {
                return ResourceManager.GetString("FeeCalculationLabel", resourceCulture);
            }
        }
        
        internal static string SortByRatingButton {
            get {
                return ResourceManager.GetString("SortByRatingButton", resourceCulture);
            }
        }
        
        internal static string SortByRoiButton {
            get {
                return ResourceManager.GetString("SortByRoiButton", resourceCulture);
            }
        }
        
        internal static string SortByStatusButton {
            get {
                return ResourceManager.GetString("SortByStatusButton", resourceCulture);
            }
        }
        
        internal static string SortByValidatorButton {
            get {
                return ResourceManager.GetString("SortByValidatorButton", resourceCulture);
            }
        }
        
        internal static string SortByMinTezButton {
            get {
                return ResourceManager.GetString("SortByMinTezButton", resourceCulture);
            }
        }
        
        internal static string BakersNotFound {
            get {
                return ResourceManager.GetString("BakersNotFound", resourceCulture);
            }
        }
        
        internal static string Bakers {
            get {
                return ResourceManager.GetString("Bakers", resourceCulture);
            }
        }
        
        internal static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        internal static string BakerIsFull {
            get {
                return ResourceManager.GetString("BakerIsFull", resourceCulture);
            }
        }
        
        internal static string DelegationInfoPageTitle {
            get {
                return ResourceManager.GetString("DelegationInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string CheckRewards {
            get {
                return ResourceManager.GetString("CheckRewards", resourceCulture);
            }
        }
        
        internal static string ChangeBaker {
            get {
                return ResourceManager.GetString("ChangeBaker", resourceCulture);
            }
        }
        
        internal static string BakerLabel {
            get {
                return ResourceManager.GetString("BakerLabel", resourceCulture);
            }
        }
        
        internal static string Roi {
            get {
                return ResourceManager.GetString("Roi", resourceCulture);
            }
        }
        
        internal static string DelegationStatus {
            get {
                return ResourceManager.GetString("DelegationStatus", resourceCulture);
            }
        }
        
        internal static string DelegationTime {
            get {
                return ResourceManager.GetString("DelegationTime", resourceCulture);
            }
        }
        
        internal static string CurrentBaker {
            get {
                return ResourceManager.GetString("CurrentBaker", resourceCulture);
            }
        }
        
        internal static string BuyWithCardPageTitle {
            get {
                return ResourceManager.GetString("BuyWithCardPageTitle", resourceCulture);
            }
        }
        
        internal static string SelectCurrencyToBuyLabel {
            get {
                return ResourceManager.GetString("SelectCurrencyToBuyLabel", resourceCulture);
            }
        }
        
        internal static string SwapInfoPageTitle {
            get {
                return ResourceManager.GetString("SwapInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string SwapInfoLabel {
            get {
                return ResourceManager.GetString("SwapInfoLabel", resourceCulture);
            }
        }
        
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        internal static string SwapInProgressDesc {
            get {
                return ResourceManager.GetString("SwapInProgressDesc", resourceCulture);
            }
        }
        
        internal static string SwapCompletedDesc {
            get {
                return ResourceManager.GetString("SwapCompletedDesc", resourceCulture);
            }
        }
        
        internal static string SwapCanceledDesc {
            get {
                return ResourceManager.GetString("SwapCanceledDesc", resourceCulture);
            }
        }
        
        internal static string SwapRefundedDesc {
            get {
                return ResourceManager.GetString("SwapRefundedDesc", resourceCulture);
            }
        }
        
        internal static string SwapUnsettledDesc {
            get {
                return ResourceManager.GetString("SwapUnsettledDesc", resourceCulture);
            }
        }
        
        internal static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        internal static string Exchanging {
            get {
                return ResourceManager.GetString("Exchanging", resourceCulture);
            }
        }
        
        internal static string Completion {
            get {
                return ResourceManager.GetString("Completion", resourceCulture);
            }
        }
        
        internal static string SwapCompleted {
            get {
                return ResourceManager.GetString("SwapCompleted", resourceCulture);
            }
        }
        
        internal static string SwapInProgress {
            get {
                return ResourceManager.GetString("SwapInProgress", resourceCulture);
            }
        }
        
        internal static string SwapCanceled {
            get {
                return ResourceManager.GetString("SwapCanceled", resourceCulture);
            }
        }
        
        internal static string SwapRefunded {
            get {
                return ResourceManager.GetString("SwapRefunded", resourceCulture);
            }
        }
        
        internal static string SwapUnsettled {
            get {
                return ResourceManager.GetString("SwapUnsettled", resourceCulture);
            }
        }
        
        internal static string InitCompleted {
            get {
                return ResourceManager.GetString("InitCompleted", resourceCulture);
            }
        }
        
        internal static string PaymentsConfirmed {
            get {
                return ResourceManager.GetString("PaymentsConfirmed", resourceCulture);
            }
        }
        
        internal static string WaitingInit {
            get {
                return ResourceManager.GetString("WaitingInit", resourceCulture);
            }
        }
        
        internal static string WaitingForPayment {
            get {
                return ResourceManager.GetString("WaitingForPayment", resourceCulture);
            }
        }
        
        internal static string WaitingForRedeem {
            get {
                return ResourceManager.GetString("WaitingForRedeem", resourceCulture);
            }
        }
        
        internal static string InitFailure {
            get {
                return ResourceManager.GetString("InitFailure", resourceCulture);
            }
        }
        
        internal static string FailedPayment {
            get {
                return ResourceManager.GetString("FailedPayment", resourceCulture);
            }
        }
        
        internal static string FailedRedeem {
            get {
                return ResourceManager.GetString("FailedRedeem", resourceCulture);
            }
        }
        
        internal static string CurrencyReceived {
            get {
                return ResourceManager.GetString("CurrencyReceived", resourceCulture);
            }
        }
        
        internal static string CurrencyRefunded {
            get {
                return ResourceManager.GetString("CurrencyRefunded", resourceCulture);
            }
        }
        
        internal static string SwapListPageTitle {
            get {
                return ResourceManager.GetString("SwapListPageTitle", resourceCulture);
            }
        }
        
        internal static string CreateSwapPageTitle {
            get {
                return ResourceManager.GetString("CreateSwapPageTitle", resourceCulture);
            }
        }
        
        internal static string SelectCurrenciesLabel {
            get {
                return ResourceManager.GetString("SelectCurrenciesLabel", resourceCulture);
            }
        }
        
        internal static string EstimatedPriceLabel {
            get {
                return ResourceManager.GetString("EstimatedPriceLabel", resourceCulture);
            }
        }
        
        internal static string EstimatedNetworkFeeLabel {
            get {
                return ResourceManager.GetString("EstimatedNetworkFeeLabel", resourceCulture);
            }
        }
        
        internal static string EnterAmountLabel {
            get {
                return ResourceManager.GetString("EnterAmountLabel", resourceCulture);
            }
        }
        
        internal static string AvailableMarketVolumeLabel {
            get {
                return ResourceManager.GetString("AvailableMarketVolumeLabel", resourceCulture);
            }
        }
        
        internal static string NoLiquidityLabel {
            get {
                return ResourceManager.GetString("NoLiquidityLabel", resourceCulture);
            }
        }
        
        internal static string PaymentFeeLabel {
            get {
                return ResourceManager.GetString("PaymentFeeLabel", resourceCulture);
            }
        }
        
        internal static string RedeemFeeLabel {
            get {
                return ResourceManager.GetString("RedeemFeeLabel", resourceCulture);
            }
        }
        
        internal static string MakerFeeLabel {
            get {
                return ResourceManager.GetString("MakerFeeLabel", resourceCulture);
            }
        }
        
        internal static string RewardForRedeemLabel {
            get {
                return ResourceManager.GetString("RewardForRedeemLabel", resourceCulture);
            }
        }
        
        internal static string TotalNetworkFeeLabel {
            get {
                return ResourceManager.GetString("TotalNetworkFeeLabel", resourceCulture);
            }
        }
        
        internal static string NoSwapsLabel {
            get {
                return ResourceManager.GetString("NoSwapsLabel", resourceCulture);
            }
        }
        
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        internal static string CreateSwapButton {
            get {
                return ResourceManager.GetString("CreateSwapButton", resourceCulture);
            }
        }
        
        internal static string ExchangePageTitle {
            get {
                return ResourceManager.GetString("ExchangePageTitle", resourceCulture);
            }
        }
        
        internal static string ExchangeLabel {
            get {
                return ResourceManager.GetString("ExchangeLabel", resourceCulture);
            }
        }
        
        internal static string ExchangeButton {
            get {
                return ResourceManager.GetString("ExchangeButton", resourceCulture);
            }
        }
        
        internal static string ChooseFromCurrency {
            get {
                return ResourceManager.GetString("ChooseFromCurrency", resourceCulture);
            }
        }
        
        internal static string ChooseToCurrency {
            get {
                return ResourceManager.GetString("ChooseToCurrency", resourceCulture);
            }
        }
        
        internal static string ExchangeHistory {
            get {
                return ResourceManager.GetString("ExchangeHistory", resourceCulture);
            }
        }
        
        internal static string ChangeRedeemAddress {
            get {
                return ResourceManager.GetString("ChangeRedeemAddress", resourceCulture);
            }
        }
        
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        internal static string TezosTokens {
            get {
                return ResourceManager.GetString("TezosTokens", resourceCulture);
            }
        }
        
        internal static string ManageTezosTokens {
            get {
                return ResourceManager.GetString("ManageTezosTokens", resourceCulture);
            }
        }
        
        internal static string HideLowBalances {
            get {
                return ResourceManager.GetString("HideLowBalances", resourceCulture);
            }
        }
        
        internal static string TokenInfoPageTitle {
            get {
                return ResourceManager.GetString("TokenInfoPageTitle", resourceCulture);
            }
        }
        
        internal static string NoTokensLabel {
            get {
                return ResourceManager.GetString("NoTokensLabel", resourceCulture);
            }
        }
        
        internal static string NoTransfersLabel {
            get {
                return ResourceManager.GetString("NoTransfersLabel", resourceCulture);
            }
        }
        
        internal static string TokenBalanceUpdatingLabel {
            get {
                return ResourceManager.GetString("TokenBalanceUpdatingLabel", resourceCulture);
            }
        }
        
        internal static string UpdateTokenButton {
            get {
                return ResourceManager.GetString("UpdateTokenButton", resourceCulture);
            }
        }
        
        internal static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
        
        internal static string TokenBalance {
            get {
                return ResourceManager.GetString("TokenBalance", resourceCulture);
            }
        }
        
        internal static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string TokenId {
            get {
                return ResourceManager.GetString("TokenId", resourceCulture);
            }
        }
        
        internal static string TokenContract {
            get {
                return ResourceManager.GetString("TokenContract", resourceCulture);
            }
        }
        
        internal static string ShowInIpfsButton {
            get {
                return ResourceManager.GetString("ShowInIpfsButton", resourceCulture);
            }
        }
        
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string PeriodInactivePageTitle {
            get {
                return ResourceManager.GetString("PeriodInactivePageTitle", resourceCulture);
            }
        }
        
        internal static string BalanceUpdateIntervalPageTitle {
            get {
                return ResourceManager.GetString("BalanceUpdateIntervalPageTitle", resourceCulture);
            }
        }
        
        internal static string AutomaticSignOutLabel {
            get {
                return ResourceManager.GetString("AutomaticSignOutLabel", resourceCulture);
            }
        }
        
        internal static string PeriodOfInactiveLabel {
            get {
                return ResourceManager.GetString("PeriodOfInactiveLabel", resourceCulture);
            }
        }
        
        internal static string UseBiometricLabel {
            get {
                return ResourceManager.GetString("UseBiometricLabel", resourceCulture);
            }
        }
        
        internal static string DeletingWallet {
            get {
                return ResourceManager.GetString("DeletingWallet", resourceCulture);
            }
        }
        
        internal static string DeletingWalletText {
            get {
                return ResourceManager.GetString("DeletingWalletText", resourceCulture);
            }
        }
        
        internal static string DeletingWalletConfirmationText {
            get {
                return ResourceManager.GetString("DeletingWalletConfirmationText", resourceCulture);
            }
        }
        
        internal static string AccountSection {
            get {
                return ResourceManager.GetString("AccountSection", resourceCulture);
            }
        }
        
        internal static string SecuritySection {
            get {
                return ResourceManager.GetString("SecuritySection", resourceCulture);
            }
        }
        
        internal static string CommunitySection {
            get {
                return ResourceManager.GetString("CommunitySection", resourceCulture);
            }
        }
        
        internal static string WalletsSection {
            get {
                return ResourceManager.GetString("WalletsSection", resourceCulture);
            }
        }
        
        internal static string CommonSection {
            get {
                return ResourceManager.GetString("CommonSection", resourceCulture);
            }
        }
        
        internal static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
        
        internal static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        internal static string PortfolioTab {
            get {
                return ResourceManager.GetString("PortfolioTab", resourceCulture);
            }
        }
        
        internal static string WalletsTab {
            get {
                return ResourceManager.GetString("WalletsTab", resourceCulture);
            }
        }
        
        internal static string ConversionTab {
            get {
                return ResourceManager.GetString("ConversionTab", resourceCulture);
            }
        }
        
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        internal static string BuyTab {
            get {
                return ResourceManager.GetString("BuyTab", resourceCulture);
            }
        }
        
        internal static string EnableBiometricLabel {
            get {
                return ResourceManager.GetString("EnableBiometricLabel", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        internal static string SuccessDelegation {
            get {
                return ResourceManager.GetString("SuccessDelegation", resourceCulture);
            }
        }
        
        internal static string DelegationListWillBeUpdated {
            get {
                return ResourceManager.GetString("DelegationListWillBeUpdated", resourceCulture);
            }
        }
        
        internal static string ExplorerUri {
            get {
                return ResourceManager.GetString("ExplorerUri", resourceCulture);
            }
        }
        
        internal static string CurrencySentToAddress {
            get {
                return ResourceManager.GetString("CurrencySentToAddress", resourceCulture);
            }
        }
        
        internal static string SuccessSending {
            get {
                return ResourceManager.GetString("SuccessSending", resourceCulture);
            }
        }
        
        internal static string isNotInWordlist {
            get {
                return ResourceManager.GetString("isNotInWordlist", resourceCulture);
            }
        }
        
        internal static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        internal static string TransactionIdCopied {
            get {
                return ResourceManager.GetString("TransactionIdCopied", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        internal static string PasswordHasInsufficientComplexity {
            get {
                return ResourceManager.GetString("PasswordHasInsufficientComplexity", resourceCulture);
            }
        }
        
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        internal static string InvalidMnemonic {
            get {
                return ResourceManager.GetString("InvalidMnemonic", resourceCulture);
            }
        }
        
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        internal static string InsufficientChainFunds {
            get {
                return ResourceManager.GetString("InsufficientChainFunds", resourceCulture);
            }
        }
        
        internal static string SufficientNetworkFee {
            get {
                return ResourceManager.GetString("SufficientNetworkFee", resourceCulture);
            }
        }
        
        internal static string TooHighNetworkFee {
            get {
                return ResourceManager.GetString("TooHighNetworkFee", resourceCulture);
            }
        }
        
        internal static string TotalNetworkFeeDetail {
            get {
                return ResourceManager.GetString("TotalNetworkFeeDetail", resourceCulture);
            }
        }
        
        internal static string LowFees {
            get {
                return ResourceManager.GetString("LowFees", resourceCulture);
            }
        }
        
        internal static string NetworkFee {
            get {
                return ResourceManager.GetString("NetworkFee", resourceCulture);
            }
        }
        
        internal static string FailedToSend {
            get {
                return ResourceManager.GetString("FailedToSend", resourceCulture);
            }
        }
        
        internal static string FailedToConvert {
            get {
                return ResourceManager.GetString("FailedToConvert", resourceCulture);
            }
        }
        
        internal static string PriceChanged {
            get {
                return ResourceManager.GetString("PriceChanged", resourceCulture);
            }
        }
        
        internal static string SwapCreated {
            get {
                return ResourceManager.GetString("SwapCreated", resourceCulture);
            }
        }
        
        internal static string GenerateMnemonic {
            get {
                return ResourceManager.GetString("GenerateMnemonic", resourceCulture);
            }
        }
        
        internal static string EmptyClipboard {
            get {
                return ResourceManager.GetString("EmptyClipboard", resourceCulture);
            }
        }
        
        internal static string EmptyWalletName {
            get {
                return ResourceManager.GetString("EmptyWalletName", resourceCulture);
            }
        }
        
        internal static string InvalidWalletName {
            get {
                return ResourceManager.GetString("InvalidWalletName", resourceCulture);
            }
        }
        
        internal static string WalletAlreadyExists {
            get {
                return ResourceManager.GetString("WalletAlreadyExists", resourceCulture);
            }
        }
        
        internal static string BakerIsDeactivated {
            get {
                return ResourceManager.GetString("BakerIsDeactivated", resourceCulture);
            }
        }
        
        internal static string AlreadyDelegatedFrom {
            get {
                return ResourceManager.GetString("AlreadyDelegatedFrom", resourceCulture);
            }
        }
        
        internal static string AutofillTransactionFailed {
            get {
                return ResourceManager.GetString("AutofillTransactionFailed", resourceCulture);
            }
        }
        
        internal static string SuccessfulCheck {
            get {
                return ResourceManager.GetString("SuccessfulCheck", resourceCulture);
            }
        }
        
        internal static string AddressSharing {
            get {
                return ResourceManager.GetString("AddressSharing", resourceCulture);
            }
        }
        
        internal static string MyPublicAddress {
            get {
                return ResourceManager.GetString("MyPublicAddress", resourceCulture);
            }
        }
        
        internal static string HasBeenUpdated {
            get {
                return ResourceManager.GetString("HasBeenUpdated", resourceCulture);
            }
        }
        
        internal static string AddressCopied {
            get {
                return ResourceManager.GetString("AddressCopied", resourceCulture);
            }
        }
        
        internal static string CopyError {
            get {
                return ResourceManager.GetString("CopyError", resourceCulture);
            }
        }
        
        internal static string CreateWalletError {
            get {
                return ResourceManager.GetString("CreateWalletError", resourceCulture);
            }
        }
        
        internal static string EmptyAddressError {
            get {
                return ResourceManager.GetString("EmptyAddressError", resourceCulture);
            }
        }
        
        internal static string InvalidAddressError {
            get {
                return ResourceManager.GetString("InvalidAddressError", resourceCulture);
            }
        }
        
        internal static string InvalidTokenContract {
            get {
                return ResourceManager.GetString("InvalidTokenContract", resourceCulture);
            }
        }
        
        internal static string InvalidFromAddress {
            get {
                return ResourceManager.GetString("InvalidFromAddress", resourceCulture);
            }
        }
        
        internal static string InsufficientChainFundsWithDetails {
            get {
                return ResourceManager.GetString("InsufficientChainFundsWithDetails", resourceCulture);
            }
        }
        
        internal static string SendingTransactionError {
            get {
                return ResourceManager.GetString("SendingTransactionError", resourceCulture);
            }
        }
        
        internal static string DelegationError {
            get {
                return ResourceManager.GetString("DelegationError", resourceCulture);
            }
        }
        
        internal static string DelegationValidationError {
            get {
                return ResourceManager.GetString("DelegationValidationError", resourceCulture);
            }
        }
        
        internal static string NoTezosError {
            get {
                return ResourceManager.GetString("NoTezosError", resourceCulture);
            }
        }
        
        internal static string AmountLessThanZeroError {
            get {
                return ResourceManager.GetString("AmountLessThanZeroError", resourceCulture);
            }
        }
        
        internal static string NoLiquidityError {
            get {
                return ResourceManager.GetString("NoLiquidityError", resourceCulture);
            }
        }
        
        internal static string PriceChangedError {
            get {
                return ResourceManager.GetString("PriceChangedError", resourceCulture);
            }
        }
        
        internal static string OrderRejectedError {
            get {
                return ResourceManager.GetString("OrderRejectedError", resourceCulture);
            }
        }
        
        internal static string TimeoutReachedError {
            get {
                return ResourceManager.GetString("TimeoutReachedError", resourceCulture);
            }
        }
        
        internal static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        internal static string AvailableFundsError {
            get {
                return ResourceManager.GetString("AvailableFundsError", resourceCulture);
            }
        }
        
        internal static string CommissionLessThanZeroError {
            get {
                return ResourceManager.GetString("CommissionLessThanZeroError", resourceCulture);
            }
        }
        
        internal static string EmptyMnemonicError {
            get {
                return ResourceManager.GetString("EmptyMnemonicError", resourceCulture);
            }
        }
        
        internal static string MnemonicWordCountError {
            get {
                return ResourceManager.GetString("MnemonicWordCountError", resourceCulture);
            }
        }
        
        internal static string WrongDelegationAddressError {
            get {
                return ResourceManager.GetString("WrongDelegationAddressError", resourceCulture);
            }
        }
        
        internal static string DelegationLimitWarning {
            get {
                return ResourceManager.GetString("DelegationLimitWarning", resourceCulture);
            }
        }
        
        internal static string BakerIsOverdelegatedWarning {
            get {
                return ResourceManager.GetString("BakerIsOverdelegatedWarning", resourceCulture);
            }
        }
        
        internal static string RemoveTxWarning {
            get {
                return ResourceManager.GetString("RemoveTxWarning", resourceCulture);
            }
        }
        
        internal static string UpdateApp {
            get {
                return ResourceManager.GetString("UpdateApp", resourceCulture);
            }
        }
        
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NotSupportSecureStorage {
            get {
                return ResourceManager.GetString("NotSupportSecureStorage", resourceCulture);
            }
        }
        
        internal static string NeedPermissionsForBiometricLogin {
            get {
                return ResourceManager.GetString("NeedPermissionsForBiometricLogin", resourceCulture);
            }
        }
        
        internal static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        internal static string SorryLabel {
            get {
                return ResourceManager.GetString("SorryLabel", resourceCulture);
            }
        }
        
        internal static string ImpossibleEnableBiometric {
            get {
                return ResourceManager.GetString("ImpossibleEnableBiometric", resourceCulture);
            }
        }
        
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        internal static string SwapHistoryText {
            get {
                return ResourceManager.GetString("SwapHistoryText", resourceCulture);
            }
        }
        
        internal static string CopyingPrivateKeyWarning {
            get {
                return ResourceManager.GetString("CopyingPrivateKeyWarning", resourceCulture);
            }
        }
        
        internal static string PrivateKeyCopied {
            get {
                return ResourceManager.GetString("PrivateKeyCopied", resourceCulture);
            }
        }
        
        internal static string MinimumAllowedQtyWarning {
            get {
                return ResourceManager.GetString("MinimumAllowedQtyWarning", resourceCulture);
            }
        }
        
        internal static string NotSupportedSymbol {
            get {
                return ResourceManager.GetString("NotSupportedSymbol", resourceCulture);
            }
        }
        
        internal static string ServicesUnavailable {
            get {
                return ResourceManager.GetString("ServicesUnavailable", resourceCulture);
            }
        }
        
        internal static string BigAmount {
            get {
                return ResourceManager.GetString("BigAmount", resourceCulture);
            }
        }
        
        internal static string BiometricAuthEnabled {
            get {
                return ResourceManager.GetString("BiometricAuthEnabled", resourceCulture);
            }
        }
        
        internal static string AmountToFeeRatioToolTip {
            get {
                return ResourceManager.GetString("AmountToFeeRatioToolTip", resourceCulture);
            }
        }
        
        internal static string MaxAmountToSendRecommendation {
            get {
                return ResourceManager.GetString("MaxAmountToSendRecommendation", resourceCulture);
            }
        }
        
        internal static string MaxAmountToSendRecommendationDetails {
            get {
                return ResourceManager.GetString("MaxAmountToSendRecommendationDetails", resourceCulture);
            }
        }
        
        internal static string MaxAmountToSendWithActiveSwaps {
            get {
                return ResourceManager.GetString("MaxAmountToSendWithActiveSwaps", resourceCulture);
            }
        }
        
        internal static string MaxAmountToSendWithActiveSwapsDetails {
            get {
                return ResourceManager.GetString("MaxAmountToSendWithActiveSwapsDetails", resourceCulture);
            }
        }
        
        internal static string SendEnteredAmountMenu {
            get {
                return ResourceManager.GetString("SendEnteredAmountMenu", resourceCulture);
            }
        }
        
        internal static string SendRecommendedAmountMenu {
            get {
                return ResourceManager.GetString("SendRecommendedAmountMenu", resourceCulture);
            }
        }
        
        internal static string OrderMatched {
            get {
                return ResourceManager.GetString("OrderMatched", resourceCulture);
            }
        }
        
        internal static string AvailableAmountDexTooltip {
            get {
                return ResourceManager.GetString("AvailableAmountDexTooltip", resourceCulture);
            }
        }
        
        internal static string AddressIsNotAtomex {
            get {
                return ResourceManager.GetString("AddressIsNotAtomex", resourceCulture);
            }
        }
        
        internal static string AddressIsNotAtomexToolTip {
            get {
                return ResourceManager.GetString("AddressIsNotAtomexToolTip", resourceCulture);
            }
        }
        
        internal static string RedeemFromAddressNote {
            get {
                return ResourceManager.GetString("RedeemFromAddressNote", resourceCulture);
            }
        }
        
        internal static string RedeemFromAddressNoteToolTip {
            get {
                return ResourceManager.GetString("RedeemFromAddressNoteToolTip", resourceCulture);
            }
        }
        
        internal static string UndelegateWarning {
            get {
                return ResourceManager.GetString("UndelegateWarning", resourceCulture);
            }
        }
        
        internal static string ContractAddress {
            get {
                return ResourceManager.GetString("ContractAddress", resourceCulture);
            }
        }
        
        internal static string ViewOnObjktButton {
            get {
                return ResourceManager.GetString("ViewOnObjktButton", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string ManageTezosCollectibles {
            get {
                return ResourceManager.GetString("ManageTezosCollectibles", resourceCulture);
            }
        }
        
        internal static string Dapps {
            get {
                return ResourceManager.GetString("Dapps", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        internal static string IncorrectQrCodeFormat {
            get {
                return ResourceManager.GetString("IncorrectQrCodeFormat", resourceCulture);
            }
        }
        
        internal static string DappId {
            get {
                return ResourceManager.GetString("DappId", resourceCulture);
            }
        }
        
        internal static string DappIsConnected {
            get {
                return ResourceManager.GetString("DappIsConnected", resourceCulture);
            }
        }
        
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        internal static string ConnectedToAddress {
            get {
                return ResourceManager.GetString("ConnectedToAddress", resourceCulture);
            }
        }
        
        internal static string ConnectDapp {
            get {
                return ResourceManager.GetString("ConnectDapp", resourceCulture);
            }
        }
        
        internal static string ConnectedSuccessfully {
            get {
                return ResourceManager.GetString("ConnectedSuccessfully", resourceCulture);
            }
        }
        
        internal static string ConnectToTrustSites {
            get {
                return ResourceManager.GetString("ConnectToTrustSites", resourceCulture);
            }
        }
        
        internal static string AppIsRequestingPermissions {
            get {
                return ResourceManager.GetString("AppIsRequestingPermissions", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDisconnect {
            get {
                return ResourceManager.GetString("AreYouSureToDisconnect", resourceCulture);
            }
        }
        
        internal static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        internal static string DisconnectDappTitle {
            get {
                return ResourceManager.GetString("DisconnectDappTitle", resourceCulture);
            }
        }
        
        internal static string DisconnectedSuccessfully {
            get {
                return ResourceManager.GetString("DisconnectedSuccessfully", resourceCulture);
            }
        }
        
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        internal static string DoYouWantToSignData {
            get {
                return ResourceManager.GetString("DoYouWantToSignData", resourceCulture);
            }
        }
        
        internal static string AddressToConnect {
            get {
                return ResourceManager.GetString("AddressToConnect", resourceCulture);
            }
        }
        
        internal static string DappWantsToConnect {
            get {
                return ResourceManager.GetString("DappWantsToConnect", resourceCulture);
            }
        }
        
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        internal static string DisplayTxDetails {
            get {
                return ResourceManager.GetString("DisplayTxDetails", resourceCulture);
            }
        }
        
        internal static string HideTxDetails {
            get {
                return ResourceManager.GetString("HideTxDetails", resourceCulture);
            }
        }
        
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        internal static string DappPairingRequest {
            get {
                return ResourceManager.GetString("DappPairingRequest", resourceCulture);
            }
        }
        
        internal static string ScanQr {
            get {
                return ResourceManager.GetString("ScanQr", resourceCulture);
            }
        }
        
        internal static string PasteQr {
            get {
                return ResourceManager.GetString("PasteQr", resourceCulture);
            }
        }
        
        internal static string GasFeeLabel {
            get {
                return ResourceManager.GetString("GasFeeLabel", resourceCulture);
            }
        }
        
        internal static string StorageLimitLabel {
            get {
                return ResourceManager.GetString("StorageLimitLabel", resourceCulture);
            }
        }
        
        internal static string StorageFeeLabel {
            get {
                return ResourceManager.GetString("StorageFeeLabel", resourceCulture);
            }
        }
        
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        internal static string TotalFees {
            get {
                return ResourceManager.GetString("TotalFees", resourceCulture);
            }
        }
        
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        internal static string Raw {
            get {
                return ResourceManager.GetString("Raw", resourceCulture);
            }
        }
        
        internal static string DappRequestToConfirm {
            get {
                return ResourceManager.GetString("DappRequestToConfirm", resourceCulture);
            }
        }
        
        internal static string ChangingTxFeeWarning {
            get {
                return ResourceManager.GetString("ChangingTxFeeWarning", resourceCulture);
            }
        }
    }
}
